version: "3.9.4"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_SESSION=${BOT_SESSION}
      - OWNER_ID=${OWNER_ID}
      - DATABASE_URI=${DATABASE_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - SESSION=${SESSION}
      - TO_CHANNEL:=${TO_CHANNEL}
      - BOT_USERNAME=${BOT_USERNAME}
